### ISSUE TITLE
Error in file_averaging.py

### ISSUE THREAD

**Issue by basilahamed94** [antoine77340/Youtube-8M-WILLOW#1]
You mentioned to run final_averaging.py, but i guess you meant file_averaging.py

$ python file_averaging.py 
Traceback (most recent call last):
  File "file_averaging.py", line 64, in <module>
    avg = read_models(model_weights1)
NameError: name 'model_weights1' is not defined

**Comment by antoine77340** [comment]
It's fixed sorry for the problem !
