### ISSUE TITLE
Question about map.

### ISSUE THREAD

**Issue by wincle** [antoine77340/Youtube-8M-WILLOW#13]
Hers is the evaluate result.
INFO:tensorflow:epoch/eval number 300001 | Avg_Hit@1: 0.848 | Avg_PERR: 0.726 | MAP: 0.077 | GAP: 0.8038 | Avg_Loss: 5.594060

MAP is so low, is that normal?

**Comment by antoine77340** [comment]
hmmm I have strictly no idea. It is very strange because the other metrics are quite ok. Are you sure you did not modify the mAP function ? The mAP should be lower than any other metric but not that low.

**Comment by wincle** [comment]
I found why did it happened , because my test datasets is small and some labels didn't get results ,so there are many zero result in aps, when doing   mAP = numpy.mean(aps)  , mAP could be very small.
