### ISSUE TITLE
Context feature 'video_id' is required but could not be found.

### ISSUE THREAD

**Issue by punitagrawal32** [antoine77340/Youtube-8M-WILLOW#27]
Hello @antoine77340 

I am trying to run the GRU model in Antoine's code to the new version of the data, and this is the error I get when I run it: 
`INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, Name: , Context feature 'video_id' is required but could not be found.
`

The code runs on the older version of the data (version1), but does not run on the newer version. 

This is the code that I ran:
`python train.py --train_data_pattern=${HOME}/yt8m/v2/frame/train*.tfrecord --model=GruModel --train_dir ~/yt8m/v2/models/frame/GRU_model2 --frame_features=True --feature_names="audio" --feature_sizes="128" --batch_size=128 --base_learning_rate=0.0002 --gru_cells=1200 --learning_rate_decay=0.9 --moe_l2=1e-6 --max_step=300000 --start_new_model`

NOTE: I am running it on the audio features only. The GRU model is able to handle this (the code runs on the older data), so this should not be an issue. 

I need to run the models on the newer data only. Please suggest changes to the code, so that the model can run. 

Thanks in advance.

**Comment by estathop** [comment]
this happened because they changed the class name . Keep in mind Youtube8M video dataset gathering happened solely on video content and not audio content, until today they don't seem to care about the audio features, it will be probably implemented in the following years

**Comment by punitagrawal32** [comment]
> this happened because they changed the class name . Keep in mind Youtube8M video dataset gathering happened solely on video content and not audio content, until today they don't seem to care about the audio features, it will be probably implemented in the following years

The code runs on audio features only, also. I am able to run logistic regression, dbof and lstm on the audio features only dataset. 

Similarly, I have been told that the field 'video_id' in the older dataset has been changed to 'id' in the new dataset, which is causing this error. The solution would be to change 'video_id' to 'id' in willow's code. I just don't know where. Do you know how I can do it?

**Comment by wenching33** [comment]
@punitagrawal32 
You can try change video_id to id in readers.py
