### ISSUE TITLE
Run Inference Error  Feature list 'audio' is required but could not be found.

### ISSUE THREAD

**Issue by zhangatao** [antoine77340/Youtube-8M-WILLOW#35]
you are probably trying to process video level features whereas his code I think is for frame level features, I don't know if it would work by changing --feature_names="rgb,audio" to --feature_names="mean_rgb,mean_audio" because that's what the features from video level are supposed to be.

_Originally posted by @estathop in https://github.com/antoine77340/Youtube-8M-WILLOW/issues/16#issuecomment-389862231_

**Comment by zhangatao** [comment]
python inference.py --output_file=test-gatednetvladLF-256k-1024-80-0002-300iter-norelu-basic-gatedmoe.csv --input_data_pattern=test_data/test*.tfrecord --model=NetVLADModelLF --train_dir=youtube-8m/public/ --frame_features=True --feature_names="rgb,audio" --feature_sizes="1024,128" --batch_size=1024 --base_learning_rate=0.0002 --netvlad_cluster_size=256 --netvlad_hidden_size=1024 --moe_l2=1e-6 --iterations=300 --learning_rate_decay=0.8 --netvlad_relu=False --gating=True --moe_prob_gating=True --run_once=True --top_k=50
![image](https://user-images.githubusercontent.com/28706321/84251199-9b005100-ab3f-11ea-951b-f15c91d646a1.png)

**Comment by zhangatao** [comment]
over

**Comment by ShiqiLi047** [comment]
hello, I meet the same problem. Have you solve this problem?
