### ISSUE TITLE
Problem in inference

### ISSUE THREAD

**Issue by wincle** [antoine77340/Youtube-8M-WILLOW#6]
Hi,glad to tell you, google have released pca matrix , and now I want to write a predict function to test the original video with your model.
But I have met a question,when I set batch_size to 1,the result is strange, could you please tell me the reason?

**Comment by antoine77340** [comment]
Hi, nice where can I find the PCA matrix ?
What do you mean by, the result is strange ?

**Comment by wincle** [comment]
https://github.com/google/youtube-8m/tree/master/feature_extractor

I will show you some examples.
Batch_size = 1
VideoId,LabelConfidencePairs
02CroU5sJF8,0 0.185172 10 0.150887 1 0.138449 5 0.109823 12 0.044488
02nGlJTewwE,29 0.511784 23 0.507139 101 0.280896 47 0.254493 3732 0.207047
02wlMR97teg,9 0.473629 12 0.160266 5 0.124923 28 0.088129 162 0.062940
024I7i7X79k,5 0.476362 59 0.031393 28 0.030166 99 0.023305 4306 0.021818
02Ty2uKOX8o,1 0.099569 0 0.067568 12 0.065813 25 0.015133 4 0.006418
02O6_Uo5YAY,4 0.611418 1 0.601294 11 0.527496 27 0.524047 140 0.395503
 
Batch_size = 1024
VideoId,LabelConfidencePairs
02CroU5sJF8,1532 0.987504 13 0.927593 203 0.592499 44 0.166606 49 0.123733
02nGlJTewwE,23 0.999564 29 0.992500 37 0.873271 101 0.791565 72 0.020543
02wlMR97teg,9 0.994120 162 0.014822 31 0.010581 28 0.003313 125 0.002859
024I7i7X79k,5 0.952463 59 0.840790 112 0.817693 316 0.811551 115 0.379988
02Ty2uKOX8o,489 0.999490 799 0.998416 922 0.996839 0 0.973660 88 0.012576
02O6_Uo5YAY,25 0.999876 140 0.999751 1 0.999242 1079 0.989948 4 0.782601

Do you know why did this happened ? Will batch size influence the result?

**Comment by antoine77340** [comment]
hmm interesting, what do you have for batch_size=2 ?

**Comment by wincle** [comment]
batch_size=2
02CroU5sJF8,1532 0.782558 13 0.444213 203 0.098820 49 0.098376 5 0.052960
02nGlJTewwE,23 0.866659 29 0.831185 101 0.482817 37 0.289396 72 0.147719
02wlMR97teg,9 0.876110 12 0.005174 10 0.004344 125 0.002876 28 0.002804
024I7i7X79k,5 0.882285 59 0.115220 115 0.053546 16 0.040082 112 0.039350
02Ty2uKOX8o,489 0.794376 799 0.793294 922 0.646738 0 0.643304 3798 0.024122
02O6_Uo5YAY,1 0.976747 27 0.715610 4 0.605781 25 0.534893 140 0.453103
 batch_size=5
02CroU5sJF8,1532 0.930521 13 0.826568 203 0.529935 44 0.103774 49 0.049890
02nGlJTewwE,23 0.940577 29 0.895074 37 0.489027 101 0.420864 47 0.080035
02wlMR97teg,9 0.968570 31 0.009148 20 0.005905 28 0.004613 330 0.003526
024I7i7X79k,5 0.941130 59 0.357349 115 0.212040 112 0.207503 316 0.159772
02Ty2uKOX8o,489 0.957871 799 0.954399 0 0.926531 922 0.921173 215 0.016986
02O6_Uo5YAY,25 0.974456 140 0.966654 1079 0.930664 1 0.893630 27 0.548143
batch_size=10
02CroU5sJF8,1532 0.951872 13 0.848458 203 0.310138 44 0.102425 49 0.046046
02nGlJTewwE,23 0.988592 29 0.971235 37 0.871994 101 0.765916 47 0.028579
02wlMR97teg,9 0.981139 28 0.010867 31 0.005758 20 0.004543 125 0.003393
024I7i7X79k,5 0.949495 59 0.664230 112 0.641454 316 0.494455 115 0.406213
02Ty2uKOX8o,489 0.987006 799 0.974236 0 0.971112 922 0.936108 12 0.021660
02O6_Uo5YAY,25 0.992420 140 0.984995 1 0.983957 1079 0.943268 27 0.658107

Have you try to change batch size in inference?

**Comment by antoine77340** [comment]
It's very interesting, I have tried changing batch size for inference of course, but nothing changed.
Are you sure you did not put any batch normalization activation during inference ? Because this is the only thing that makes the output varies depending on the input batch size.

**Comment by wincle** [comment]
I will check it again .
 Is there any possible that my trained model has mistakes?

**Comment by antoine77340** [comment]
I don't think so, If you took the same code and run the same training command as mine, you should not have any problem.

**Comment by wincle** [comment]
Now the problems seems to be solved, but  I found many videos tend to belong Food class. Is that normal?

**Comment by wincle** [comment]
I'm sure there are some problems in inference and I  didn't put any batch normalization activation.
Now I use batch to inference could get right results but use single to inference get wrong result. Do you know why?

**Comment by wincle** [comment]
I have frozen your models and put the graph nodes, then I get these:
train_input/shuffle_batch_join/random_shuffle_queue
train_input/shuffle_batch_join/n
train_input/shuffle_batch_join
l2_normalize/Square
l2_normalize/Sum/reduction_indices
l2_normalize/Sum
l2_normalize/Maximum/y
l2_normalize/Maximum
l2_normalize/Rsqrt
l2_normalize
model/ExpandDims/dim
model/ExpandDims
model/Cast
model/Shape
model/strided_slice/stack
model/strided_slice/stack_1
model/strided_slice/stack_2
model/strided_slice
model/random_uniform/shape/1
model/random_uniform/shape
model/random_uniform/min
model/random_uniform/max
model/random_uniform/RandomUniform
model/random_uniform/sub
model/random_uniform/mul
model/random_uniform
model/Tile/multiples
model/Tile
model/Mul
model/Cast_2
model/range/start
model/range/delta
model/range
model/ExpandDims_1/dim
model/ExpandDims_1
model/Tile_1/multiples
model/Tile_1
model/stack
model/GatherNd
model/Reshape/shape
model/Reshape
input_bn/beta
input_bn/beta/read
input_bn/gamma
input_bn/gamma/read
model/input_bn/moments/Mean/reduction_indices
model/input_bn/moments/Mean
model/input_bn/moments/StopGradient
model/input_bn/moments/sufficient_statistics/Shape
model/input_bn/moments/sufficient_statistics/Cast
model/input_bn/moments/sufficient_statistics/Gather/indices
model/input_bn/moments/sufficient_statistics/Gather
model/input_bn/moments/sufficient_statistics/Const
model/input_bn/moments/sufficient_statistics/count
model/input_bn/moments/sufficient_statistics/Sub
model/input_bn/moments/sufficient_statistics/SquaredDifference
model/input_bn/moments/sufficient_statistics/mean_ss/reduction_indices
model/input_bn/moments/sufficient_statistics/mean_ss
model/input_bn/moments/sufficient_statistics/var_ss/reduction_indices
model/input_bn/moments/sufficient_statistics/var_ss
model/input_bn/moments/Shape
model/input_bn/moments/Reshape
model/input_bn/moments/normalize/divisor
model/input_bn/moments/normalize/shifted_mean
model/input_bn/moments/normalize/mean
model/input_bn/moments/normalize/Mul
model/input_bn/moments/normalize/Square
model/input_bn/moments/normalize/variance
model/input_bn/batchnorm/add/y
model/input_bn/batchnorm/add
model/input_bn/batchnorm/Rsqrt
model/input_bn/batchnorm/mul
model/input_bn/batchnorm/mul_1
model/input_bn/batchnorm/mul_2
model/input_bn/batchnorm/sub
model/input_bn/batchnorm/add_1
model/video_VLAD/strided_slice/stack
model/video_VLAD/strided_slice/stack_1
model/video_VLAD/strided_slice/stack_2
model/video_VLAD/strided_slice
video_VLAD/cluster_weights
video_VLAD/cluster_weights/read
model/video_VLAD/MatMul
video_VLAD/cluster_bn/beta
video_VLAD/cluster_bn/beta/read
video_VLAD/cluster_bn/gamma
video_VLAD/cluster_bn/gamma/read
model/video_VLAD/cluster_bn/moments/Mean/reduction_indices
model/video_VLAD/cluster_bn/moments/Mean
model/video_VLAD/cluster_bn/moments/StopGradient
model/video_VLAD/cluster_bn/moments/sufficient_statistics/Shape
model/video_VLAD/cluster_bn/moments/sufficient_statistics/Cast
model/video_VLAD/cluster_bn/moments/sufficient_statistics/Gather/indices
model/video_VLAD/cluster_bn/moments/sufficient_statistics/Gather
model/video_VLAD/cluster_bn/moments/sufficient_statistics/Const
model/video_VLAD/cluster_bn/moments/sufficient_statistics/count
model/video_VLAD/cluster_bn/moments/sufficient_statistics/Sub
model/video_VLAD/cluster_bn/moments/sufficient_statistics/SquaredDifference
model/video_VLAD/cluster_bn/moments/sufficient_statistics/mean_ss/reduction_indices
model/video_VLAD/cluster_bn/moments/sufficient_statistics/mean_ss
model/video_VLAD/cluster_bn/moments/sufficient_statistics/var_ss/reduction_indices
model/video_VLAD/cluster_bn/moments/sufficient_statistics/var_ss
model/video_VLAD/cluster_bn/moments/Shape
model/video_VLAD/cluster_bn/moments/Reshape
model/video_VLAD/cluster_bn/moments/normalize/divisor
model/video_VLAD/cluster_bn/moments/normalize/shifted_mean
model/video_VLAD/cluster_bn/moments/normalize/mean
model/video_VLAD/cluster_bn/moments/normalize/Mul
model/video_VLAD/cluster_bn/moments/normalize/Square
model/video_VLAD/cluster_bn/moments/normalize/variance
model/video_VLAD/cluster_bn/batchnorm/add/y
model/video_VLAD/cluster_bn/batchnorm/add
model/video_VLAD/cluster_bn/batchnorm/Rsqrt
model/video_VLAD/cluster_bn/batchnorm/mul
model/video_VLAD/cluster_bn/batchnorm/mul_1
model/video_VLAD/cluster_bn/batchnorm/mul_2
model/video_VLAD/cluster_bn/batchnorm/sub
model/video_VLAD/cluster_bn/batchnorm/add_1
model/video_VLAD/Softmax
model/video_VLAD/Reshape/shape
model/video_VLAD/Reshape
model/video_VLAD/Sum/reduction_indices
model/video_VLAD/Sum
video_VLAD/cluster_weights2
video_VLAD/cluster_weights2/read
model/video_VLAD/Mul
model/video_VLAD/transpose/perm
model/video_VLAD/transpose
model/video_VLAD/Reshape_1/shape
model/video_VLAD/Reshape_1
model/video_VLAD/MatMul_1
model/video_VLAD/transpose_1/perm
model/video_VLAD/transpose_1
model/video_VLAD/Sub
model/video_VLAD/l2_normalize/Square
model/video_VLAD/l2_normalize/Sum/reduction_indices
model/video_VLAD/l2_normalize/Sum
model/video_VLAD/l2_normalize/Maximum/y
model/video_VLAD/l2_normalize/Maximum
model/video_VLAD/l2_normalize/Rsqrt
model/video_VLAD/l2_normalize
model/video_VLAD/Reshape_2/shape
model/video_VLAD/Reshape_2
model/video_VLAD/l2_normalize_1/Square
model/video_VLAD/l2_normalize_1/Sum/reduction_indices
model/video_VLAD/l2_normalize_1/Sum
model/video_VLAD/l2_normalize_1/Maximum/y
model/video_VLAD/l2_normalize_1/Maximum
model/video_VLAD/l2_normalize_1/Rsqrt
model/video_VLAD/l2_normalize_1
model/audio_VLAD/strided_slice/stack
model/audio_VLAD/strided_slice/stack_1
model/audio_VLAD/strided_slice/stack_2
model/audio_VLAD/strided_slice
audio_VLAD/cluster_weights
audio_VLAD/cluster_weights/read
model/audio_VLAD/MatMul
audio_VLAD/cluster_bn/beta
audio_VLAD/cluster_bn/beta/read
audio_VLAD/cluster_bn/gamma
audio_VLAD/cluster_bn/gamma/read
model/audio_VLAD/cluster_bn/moments/Mean/reduction_indices
model/audio_VLAD/cluster_bn/moments/Mean
model/audio_VLAD/cluster_bn/moments/StopGradient
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/Shape
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/Cast
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/Gather/indices
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/Gather
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/Const
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/count
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/Sub
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/SquaredDifference
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/mean_ss/reduction_indices
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/mean_ss
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/var_ss/reduction_indices
model/audio_VLAD/cluster_bn/moments/sufficient_statistics/var_ss
model/audio_VLAD/cluster_bn/moments/Shape
model/audio_VLAD/cluster_bn/moments/Reshape
model/audio_VLAD/cluster_bn/moments/normalize/divisor
model/audio_VLAD/cluster_bn/moments/normalize/shifted_mean
model/audio_VLAD/cluster_bn/moments/normalize/mean
model/audio_VLAD/cluster_bn/moments/normalize/Mul
model/audio_VLAD/cluster_bn/moments/normalize/Square
model/audio_VLAD/cluster_bn/moments/normalize/variance
model/audio_VLAD/cluster_bn/batchnorm/add/y
model/audio_VLAD/cluster_bn/batchnorm/add
model/audio_VLAD/cluster_bn/batchnorm/Rsqrt
model/audio_VLAD/cluster_bn/batchnorm/mul
model/audio_VLAD/cluster_bn/batchnorm/mul_1
model/audio_VLAD/cluster_bn/batchnorm/mul_2
model/audio_VLAD/cluster_bn/batchnorm/sub
model/audio_VLAD/cluster_bn/batchnorm/add_1
model/audio_VLAD/Softmax
model/audio_VLAD/Reshape/shape
model/audio_VLAD/Reshape
model/audio_VLAD/Sum/reduction_indices
model/audio_VLAD/Sum
audio_VLAD/cluster_weights2
audio_VLAD/cluster_weights2/read
model/audio_VLAD/Mul
model/audio_VLAD/transpose/perm
model/audio_VLAD/transpose
model/audio_VLAD/Reshape_1/shape
model/audio_VLAD/Reshape_1
model/audio_VLAD/MatMul_1
model/audio_VLAD/transpose_1/perm
model/audio_VLAD/transpose_1
model/audio_VLAD/Sub
model/audio_VLAD/l2_normalize/Square
model/audio_VLAD/l2_normalize/Sum/reduction_indices
model/audio_VLAD/l2_normalize/Sum
model/audio_VLAD/l2_normalize/Maximum/y
model/audio_VLAD/l2_normalize/Maximum
model/audio_VLAD/l2_normalize/Rsqrt
model/audio_VLAD/l2_normalize
model/audio_VLAD/Reshape_2/shape
model/audio_VLAD/Reshape_2
model/audio_VLAD/l2_normalize_1/Square
model/audio_VLAD/l2_normalize_1/Sum/reduction_indices
model/audio_VLAD/l2_normalize_1/Sum
model/audio_VLAD/l2_normalize_1/Maximum/y
model/audio_VLAD/l2_normalize_1/Maximum
model/audio_VLAD/l2_normalize_1/Rsqrt
model/audio_VLAD/l2_normalize_1
model/concat/axis
model/concat
hidden1_weights
hidden1_weights/read
model/MatMul
hidden1_biases
hidden1_biases/read
model/add
gating_weights_2
gating_weights_2/read
model/MatMul_1
gating_bn/beta
gating_bn/beta/read
gating_bn/gamma
gating_bn/gamma/read
model/gating_bn/moments/Mean/reduction_indices
model/gating_bn/moments/Mean
model/gating_bn/moments/StopGradient
model/gating_bn/moments/sufficient_statistics/Shape
model/gating_bn/moments/sufficient_statistics/Cast
model/gating_bn/moments/sufficient_statistics/Gather/indices
model/gating_bn/moments/sufficient_statistics/Gather
model/gating_bn/moments/sufficient_statistics/Const
model/gating_bn/moments/sufficient_statistics/count
model/gating_bn/moments/sufficient_statistics/Sub
model/gating_bn/moments/sufficient_statistics/SquaredDifference
model/gating_bn/moments/sufficient_statistics/mean_ss/reduction_indices
model/gating_bn/moments/sufficient_statistics/mean_ss
model/gating_bn/moments/sufficient_statistics/var_ss/reduction_indices
model/gating_bn/moments/sufficient_statistics/var_ss
model/gating_bn/moments/Shape
model/gating_bn/moments/Reshape
model/gating_bn/moments/normalize/divisor
model/gating_bn/moments/normalize/shifted_mean
model/gating_bn/moments/normalize/mean
model/gating_bn/moments/normalize/Mul
model/gating_bn/moments/normalize/Square
model/gating_bn/moments/normalize/variance
model/gating_bn/batchnorm/add/y
model/gating_bn/batchnorm/add
model/gating_bn/batchnorm/Rsqrt
model/gating_bn/batchnorm/mul
model/gating_bn/batchnorm/mul_1
model/gating_bn/batchnorm/mul_2
model/gating_bn/batchnorm/sub
model/gating_bn/batchnorm/add_1
model/Sigmoid
model/Mul_1
gates/weights
gates/weights/read
model/gates/MatMul
experts/weights
experts/weights/read
experts/biases
experts/biases/read
model/experts/MatMul
model/experts/BiasAdd
model/Reshape_1/shape
model/Reshape_1
model/Softmax
model/Reshape_2/shape
model/Reshape_2
model/Sigmoid_1
model/strided_slice_1/stack
model/strided_slice_1/stack_1
model/strided_slice_1/stack_2
model/strided_slice_1
model/mul
model/Sum/reduction_indices
model/Sum
model/Reshape_3/shape
model/Reshape_3
gating_prob_weights
gating_prob_weights/read
model/MatMul_2
gating_prob_bn/beta
gating_prob_bn/beta/read
gating_prob_bn/gamma
gating_prob_bn/gamma/read
model/gating_prob_bn/moments/Mean/reduction_indices
model/gating_prob_bn/moments/Mean
model/gating_prob_bn/moments/StopGradient
model/gating_prob_bn/moments/sufficient_statistics/Shape
model/gating_prob_bn/moments/sufficient_statistics/Cast
model/gating_prob_bn/moments/sufficient_statistics/Gather/indices
model/gating_prob_bn/moments/sufficient_statistics/Gather
model/gating_prob_bn/moments/sufficient_statistics/Const
model/gating_prob_bn/moments/sufficient_statistics/count
model/gating_prob_bn/moments/sufficient_statistics/Sub
model/gating_prob_bn/moments/sufficient_statistics/SquaredDifference
model/gating_prob_bn/moments/sufficient_statistics/mean_ss/reduction_indices
model/gating_prob_bn/moments/sufficient_statistics/mean_ss
model/gating_prob_bn/moments/sufficient_statistics/var_ss/reduction_indices
model/gating_prob_bn/moments/sufficient_statistics/var_ss
model/gating_prob_bn/moments/Shape
model/gating_prob_bn/moments/Reshape
model/gating_prob_bn/moments/normalize/divisor
model/gating_prob_bn/moments/normalize/shifted_mean
model/gating_prob_bn/moments/normalize/mean
model/gating_prob_bn/moments/normalize/Mul
model/gating_prob_bn/moments/normalize/Square
model/gating_prob_bn/moments/normalize/variance
model/gating_prob_bn/batchnorm/add/y
model/gating_prob_bn/batchnorm/add
model/gating_prob_bn/batchnorm/Rsqrt
model/gating_prob_bn/batchnorm/mul
model/gating_prob_bn/batchnorm/mul_1
model/gating_prob_bn/batchnorm/mul_2
model/gating_prob_bn/batchnorm/sub
model/gating_prob_bn/batchnorm/add_1
model/Sigmoid_2
model/Mul_2

There are batch normalization  activation in it , how could I remove them?

**Comment by wincle** [comment]
I think may be I found where is the mistake, I should use the export model, not the checkpoint models, am I right?

**Comment by huitang** [comment]
> I think may be I found where is the mistake, I should use the export model, not the checkpoint models, am I right?

Hi did you solve your problem\?
did you freeze your model?
or you read the downloaded file directly?
I met problems in loading the pretrained model, please help thanks a lot

**Comment by zhangatao** [comment]
> > I think may be I found where is the mistake, I should use the export model, not the checkpoint models, am I right?
> 
> Hi did you solve your problem?
> did you freeze your model?
> or you read the downloaded file directly?
> I met problems in loading the pretrained model, please help thanks a lot
Hi did you solve your problem?
I met problems in inference,  please help thanks a lot

**Comment by zhangatao** [comment]
> > I think may be I found where is the mistake, I should use the export model, not the checkpoint models, am I right?
> 
> Hi did you solve your problem?
> did you freeze your model?
> or you read the downloaded file directly?
> I met problems in loading the pretrained model, please help thanks a lot

Hi did you solve your problem?
