### ISSUE TITLE
Request your trained model

### ISSUE THREAD

**Issue by feiyun1265** [antoine77340/Youtube-8M-WILLOW#7]
Congratulations on your winning. And thanks for sharing your work. I'm very interested in the YouTube-8M Large-Scale Video Understanding project. Now, i want to use my own video test your team model. Can you send me your trained model. My email:chshfmail@163.com. Thanks.

**Comment by antoine77340** [comment]
Hi,
Yes sure, I just realized Google had released their code for feature extraction.
I will update the github repo with the pretrained best model I have (If I find it back ahha :) ).

**Comment by antoine77340** [comment]
Here it is: https://www.rocq.inria.fr/cluster-willow/amiech/pretrainedmodel.zip
This is the model for :
python inference.py --output_file=test-gatednetvladLF-256k-1024-80-0002-300iter-norelu-basic-gatedmoe.csv --input_data_pattern="$path_to_features/test*.tfrecord" --model=NetVLADModelLF --train_dir=gatednetvladLF-256k-1024-80-0002-300iter-norelu-basic-gatedmoe --frame_features=True --feature_names="rgb,audio" --feature_sizes="1024,128" --batch_size=1024 --base_learning_rate=0.0002 --netvlad_cluster_size=256 --netvlad_hidden_size=1024 --moe_l2=1e-6 --iterations=300 --learning_rate_decay=0.8 --netvlad_relu=False --gating=True --moe_prob_gating=True --run_once=True  --top_k=50

**Comment by feiyun1265** [comment]
Thanks for your sharing. @antoine77340
